### ISSUE TITLE
Imagem do podcast

### ISSUE THREAD

**Issue by zeucxb** [ogilvieira/awesome-podcasts-br#101]
Qual à imagem que vocês se baseiam para colocar na "capa" do podcast? Por que não usam a do rss?

**Comment by ogilvieira** [comment]
Olá @zeucxb o feed é parseado por uma solução do Google e chega sem alguns dados pra gente, pode nos ajudar com isso? Estamos pegando o logo do podcast pelo twitter oficial de cada um.

**Comment by zeucxb** [comment]
@ogilvieira entendi. É que geralmente o rss tem um campo com a imagem do podcast, poderiam colocar pelo menos um campo para adicionar a imagem a parte ou fazer um check para ver se consta no rss. Pois vi alguns podcasts que assim como o meu não tem um twitter oficial e ficam errados :/

Um campo para imagem já resolve, basta subir no ingur e mandar o link

**Comment by ogilvieira** [comment]
podemos dar um jeito nisso, o problema de carregar o feed é que na listagem inicial iriamos carregar muitos feeds só pra pegar a url da imagem e isso podia ser ruim pro carregamento da página

**Comment by zeucxb** [comment]
@ogilvieira não faz sentido baixar essa imagem? e ter estática no projeto?

**Comment by ogilvieira** [comment]
Cara, é mais um arquivo pra subir. O projeto é todo estático e tentamos manter o mais fácil possível para add novos podcasts, no nosso caso é necessário só adicionar um objeto num arquivo json, prezamos por isso para deixar mais fácil a atualização.

**Comment by zeucxb** [comment]
@ogilvieira justamente por isso, se hospedar a imagem em um singur da vida e te passar a url em um objeto json, você pode escolher entre usar direto o link ou fazer o download da imagem no momento do build e usar uma referencia.

**Comment by enieber** [comment]
@ogilvieira  podemos fechar essa issue ou ainda precisa de ajustes no js?
