### ISSUE TITLE
add status travis ci 

### ISSUE THREAD

**Issue by enieber** [ogilvieira/awesome-podcasts-br#110]
based in the PR #109

**Comment by leonampd** [comment]
Hey @enieber how can I help you with this issue? First of all, we need to link the repo on [travis-ci.org](travis-ci.org) and, if you are owner you can do it.

**Comment by enieber** [comment]
@ogilvieira can you help ?

**Comment by enieber** [comment]
migrate to outher repository: https://github.com/podcast-list/podcast-list.github.io/issues/4
