### ISSUE TITLE
como rodar o projeto

### ISSUE THREAD

**Issue by enieber** [ogilvieira/awesome-podcasts-br#116]
O projeto ficou  bem grandinho, como faço para rodar ele localmente?

**Comment by ogilvieira** [comment]
Após clonar com o NodeJS (https://nodejs.org/en/) instalado, pelo terminal rode:

```
npm install -g grunt-cli

npm install && bower install

grunt watch
```

**Comment by enieber** [comment]
valew @ogilvieira
