### ISSUE TITLE
Link para o  Pocket Casts

### ISSUE THREAD

**Issue by alesshh** [ogilvieira/awesome-podcasts-br#118]
Alguns podcasts possuem link p/ Pocket Casts (http://www.shiftyjelly.com/pocketcasts/), por exemplo http://pca.st/fmx9.

Seria interessante ter espaço p/ esse player.

Acredito que seja similar à #65.

**Comment by enieber** [comment]
migrando para outro repositorio: https://github.com/podcast-list/podcast-list.github.io/issues/5
