### ISSUE TITLE
Atualizar link na descrição do repositório 

### ISSUE THREAD

**Issue by gustavoclay** [ogilvieira/awesome-podcasts-br#128]
Atualizar o link do site da descrição do repositório no próprio github.

![screenshot-2018-7-1 ogilvieira awesome-podcasts-br](https://user-images.githubusercontent.com/7647563/42137311-aabaf5ca-7d40-11e8-98f6-9523de33d8f8.png)

**Comment by enieber** [comment]
@ogilvieira o novo link http://ogilvieira.github.io/awesome-podcasts-br/#/

**Comment by enieber** [comment]
@gustavoclay por enquanto resolvi assim https://github.com/podcast-list/podcast-list.github.io

**Comment by enieber** [comment]
https://podcast-list.github.io/#/
