### ISSUE TITLE
[Dúvida] Licença de uso não especificada

### ISSUE THREAD

**Issue by vandersonmr** [ogilvieira/awesome-podcasts-br#143]
Não encontrei nenhuma licença para esse projeto. Poderia adicionar ao projeto e licenciar ele como software livre ou open source?

**Comment by enieber** [comment]
@ogilvieira

**Comment by enieber** [comment]
@vandersonmr da uma olhada no [fork do proejto](https://github.com/podcast-list/podcast-list.github.io) abre uma issue la que colocaremos uma licença

**Comment by enieber** [comment]
migrando para o novo repositorio: https://github.com/podcast-list/podcast-list.github.io/issues/6
