### ISSUE TITLE
Incluir coluna para o Google Play

### ISSUE THREAD

**Issue by lvcabral** [ogilvieira/awesome-podcasts-br#65]
O Google Play agora tem suporte a Podcasts acho que deveria ser adicionada uma coluna para os links dessa plataforma.

**Comment by ogilvieira** [comment]
Opa! desculpe pela demora.

Estamos avaliando como reorganizar a lista. Como foi feita com markdown pra facilitar a contribuição, acabou que este markdown virou um monstrinho chato de dar manutenção. Provavelmente na nova versão que estamos debatendo, vai haver esta feature/coluna. 

Obrigado 🐤

**Comment by mdamaceno** [comment]
Parece que o podcast pelo Google Play ainda não está habilitado para o Brasil. Mesmo assim, é uma boa ideia para quando estiver.

**Comment by enieber** [comment]
está na faze de teste ainda, mas pra quem ja está nos lugares liberado esse é o link 

https://play.google.com/music/podcasts/publish?u=0#

**Comment by enieber** [comment]
infelismente ainda não esta disponivel para o Brasil.

![screenshot-2017-10-16 publish your podcast to google play music](https://user-images.githubusercontent.com/7907068/31608866-bfeb42d0-b250-11e7-943f-da8eebdf93e9.png)

**Comment by enieber** [comment]
provavelmente seria melhor adicionar o link para o [Google Podcasts](https://play.google.com/store/apps/details?id=com.google.android.apps.podcasts&hl=en_US)

**Comment by enieber** [comment]
migrando o projeto para um [novo repositorio](https://github.com/podcast-list/podcast-list.github.io)

**Comment by enieber** [comment]
link da issue https://github.com/podcast-list/podcast-list.github.io/issues/1
