### ISSUE TITLE
Texto da descrição tem pouco constrate e dificulta a leitura

### ISSUE THREAD

**Issue by lccezinha** [ogilvieira/awesome-podcasts-br#86]
Sugestão de alterar essa cor de texto para deixa com um contraste melhor.

![podcast](https://cloud.githubusercontent.com/assets/2160392/19535493/a31635f8-9626-11e6-8a8b-ae3f337489db.png)

**Comment by enieber** [comment]
algumas melhorias de usabilidade são sempre bem vindas.. acredito que não deva ser tão difícil de resolver esse problema. Valew pela sugestão.

**Comment by woliveiras** [comment]
@ogilvieira é ligeiro de mais... Nem da tempo de ajudar o homi! :joy: :joy: :joy:

**Comment by ogilvieira** [comment]
@woliveiras tem 2 issues abertas ainda rs uma easy mas trabalhosa e outra q eu vou precisar parar e pesquisae, pode pegar se quiser hehe. o app ta bem simples!
