### ISSUE TITLE
Automatizar atualização

### ISSUE THREAD

**Issue by enieber** [ogilvieira/awesome-podcasts-br#89]
Poderia criar um script que todo o inicio da semana atualiza os dados dos podcasts para verificar se eles estão ativos ou não...

**Comment by ogilvieira** [comment]
Mas então, podemos criar uma regra pra checar o tempo desde o lançamento do último episódio dos casts pra definirmos quem está ou não ativo. Acho que muitos podcasts têm uma frequência de 1 episódio a cada 15 dias na maioria das vezes, o que vc acha?

**Comment by enieber** [comment]
pode ser algo bem simples. fazer duas requests para verificar se o podcast foi atualizado, uma a cada 10 dias só para atualizar o status para true e outra request a cada 30 dias para atualizar o status para false.

assim mesmo que um episódio demore mais do que 30 dias, 10 dias depois ele ia atualizar o status caso tenha um episódio novo

**Comment by enieber** [comment]
migrando para novo repositorio: https://github.com/podcast-list/podcast-list.github.io/issues/3
