### ISSUE TITLE
Problema ao abrir os episodios

### ISSUE THREAD

**Issue by brunoravanhani** [ogilvieira/awesome-podcasts-br#97]
Olá, só reportando, ao clicar no podcast, não aparece nada além disso: 

![capturar](https://cloud.githubusercontent.com/assets/12189180/22506946/ce73a55e-e861-11e6-9ec7-7e05bb327f17.PNG)

**Comment by enieber** [comment]
por enquanto não estamos fazendo o import dos episódios apenas apontando para repositório de cada podcast, obrigado por perguntar...

**Comment by brunoravanhani** [comment]
Ah tá, foi mal, não sabia
